services:
  db:
    restart: on-failure
    image: postgres:12
    container_name: boat-app-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: boat_db
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
      - ./db/setup:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    restart: on-failure
    container_name: boat-app-api
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      PGSQL_HOST: db
    ports:
      - 8080:8080
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
  client:
    restart: on-failure
    container_name: boat-app-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:80
    depends_on:
      - api
