version: '3.5'

services:
   db:
      image: postgres:12
      restart: always
      environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: admin123
         POSTGRES_DB: boat_db
      ports:
         - 5432:5432
